### ISSUE TITLE
Open SSL Connection reset by peer

### ISSUE THREAD

**Issue by BenSotty** [salesforce-marketingcloud/FuelSDK-Ruby#65]
Hi,

I am trying to add a row in a data extension I have created following the `sample-dataextension.rb` _Add a row to a data extension (using CustomerKey)_. I keep on having the same error: 
`ECONNRESET: Connection reset by peer - SSL_connect`

 here is the code I run from a rails console: 
```
CLIENT_ID = "%OUR_CLIENT_ID%"
SECRET = "%OUR_SECRET%"
DE_CUSTOMER_KEY = "%OUR_DE_CUSTOMER_KEY%"
de_row_proerties = {"de_attribute" => "value"}

auth = {
  "client" => {
    "id" => CLIENT_ID,
    "secret" => SECRET
  },
  "defaultwsdl" => "https://webservice.s7.exacttarget.com/etframework.wsdl"
}

stubObj = ET_Client.new auth, true
de = ET_DataExtension::Row.new
de.CustomerKey = DE_CUSTOMER_KEY
de.authStub = stubObj
de.props = de_row_proerties
de.post
```
Here is the error I get (with the debug mode enabled) :

```
D, [2017-05-18T17:13:24.193758 #9943] DEBUG -- : HTTPI GET request to webservice.s7.exacttarget.com (httpclient)
D, [2017-05-18T17:13:24.487087 #9943] DEBUG -- : HTTPI GET request to webservice.s7.exacttarget.com (httpclient)
Errno::ECONNRESET: Connection reset by peer - SSL_connect
	from /Users/bensotty/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/httpclient-2.3.4.1/lib/httpclient/session.rb:303:in `connect'
	from /Users/bensotty/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/httpclient-2.3.4.1/lib/httpclient/session.rb:303:in `ssl_connect'
	from /Users/bensotty/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/httpclient-2.3.4.1/lib/httpclient/session.rb:760:in `block in connect'
	from /Users/bensotty/.rbenv/versions/2.2.3/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
	from /Users/bensotty/.rbenv/versions/2.2.3/lib/ruby/2.2.0/timeout.rb:98:in `call'
	from /Users/bensotty/.rbenv/versions/2.2.3/lib/ruby/2.2.0/timeout.rb:98:in `timeout'
	from /Users/bensotty/.rbenv/versions/2.2.3/lib/ruby/2.2.0/timeout.rb:124:in `timeout'
	from /Users/bensotty/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/httpclient-2.3.4.1/lib/httpclient/session.rb:751:in `connect'
	from /Users/bensotty/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/httpclient-2.3.4.1/lib/httpclient/session.rb:609:in `query'
	from /Users/bensotty/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/httpclient-2.3.4.1/lib/httpclient/session.rb:164:in `query'
	from /Users/bensotty/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/httpclient-2.3.4.1/lib/httpclient.rb:1083:in `do_get_block'
	from /Users/bensotty/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/httpclient-2.3.4.1/lib/httpclient.rb:887:in `block in do_request'
	from /Users/bensotty/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/httpclient-2.3.4.1/lib/httpclient.rb:981:in `protect_keep_alive_disconnected'
	from /Users/bensotty/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/httpclient-2.3.4.1/lib/httpclient.rb:886:in `do_request'
	from /Users/bensotty/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/httpclient-2.3.4.1/lib/httpclient.rb:774:in `request'
	from /Users/bensotty/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/httpi-2.0.2/lib/httpi/adapter/httpclient.rb:26:in `request'
```

I am running a project on rails  4.2.7.1, on my local machine, mac os 10.12.3, using OpenSSL 1.0.2k.

Any ideas ? Is this a bug on the sdk ?

Thanks for helping.

**Comment by Gokul595** [comment]
@BenSotty, 
Try removing `"defaultwsdl" => "https://webservice.s7.exacttarget.com/etframework.wsdl"` from `auth`and check it.

**Comment by BenSotty** [comment]
@Gokul595: (I just added it because I have seen that our app is hosted on S7 instance.)
I tried that already, and got the same error.

**Comment by JPMallow** [comment]
@BenSotty Did you solved this issue? I am also facing the same issue for all the APIs.
